### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dkogue** [brake/milenage#1]
Hi, 
I  would appreciate if someone can help me with the following questions.

Is possible to load this program on a programmable USIM card and test it?
If yes how to proceed, please?

Thank you!

**Comment by brake** [comment]
Hi,
AFAIK Java on smart cards is quite limited. For example, it supports a limited set of data types. I'm not sure card supports all types I've used in this project. Moreover, this project for now is not adapted for JavaCard.
